### ISSUE TITLE
Pivot output data file

### ISSUE THREAD

**Issue by gnodnooh** [HarvestStat/HarvestStat#46]
I suggest that the hvstat_data.csv file includes columns for “area,” “production,” and “yield” to reduce the size of the table. Additionally, we can consider the following options:

(a) Adding “QC_area,” “QC_production,” and “QC_yield” columns.
(b) Creating the same format but with QC_flag values, such as hvstat_flag.csv.

Personally, I lean towards option (a).

**Comment by gnodnooh** [comment]
Hi @WestonAnderson, please let me know your opinion 👍

**Comment by WestonAnderson** [comment]
Hmmm, this is a bit of a philosophical question for the QC_flag. I'd lean towards a single QC flag that applies across production, yield, and harvested area (e.g. just a single QC_flag column). Right now we flag yield values only because it's much harder to identify spurious values of production or harvested area. A spike in production may be due to an increase in harvested area due to an economic incentive, for example. But you wouldn't expect anything really leads to significant spikes in yield outside of exceptionally low yielding systems.

But if we're QC_flagging a yield observation, and yield is calculated from area and production, then there is something wrong with one of the other two values as well. So it's probably most appropriate to have a single flag that applies across yield, harvested area, and production even if we identify it using only yield.

What do you think?

**Comment by gnodnooh** [comment]
We decided to use a single QC_Flag for the current aggregation and QC approaches.
This can be expanded to QC_Area, QC_Production, QC_Yield when QC process is further developed in the future.
